name: Java CI with Maven and Deploy to AlwaysData

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          MAIL_HOST: ${{secrets.MAIL_HOST}}
          MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
          MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}


      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: shop
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: production

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: shop

      - name: FTP Deploy to AlwaysData
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.ALWAYSDATA_USERNAME }}
          password: ${{ secrets.ALWAYSDATA_PASSWORD }}
          local-dir: ./
          server-dir: /home/shop-backend/
          protocol: ftp



